### ISSUE TITLE
Custom Log Directory Structure

### ISSUE THREAD

**Issue by rakeen** [potsky/PimpMyLog#100]
I'm using a shared hosting. And my log files are stored every day in a separate file and they are also sorted in a separate directory according to their month. i.e
```
├── htdocs
├── log
    ├── access
    |   ├── 12
    |   |   ├── 1
    |   |   ├── 2
    |   |   ├── 3
    |   |   ├── 4
    |   ├── 11 
    └── error

Is there any way I could incorporate this structure and setup the PimpMyLog?

**Comment by potsky** [comment]
Hi !

Yes you can specify wildcards in the path parameter.

You can do something like this:

```
"path" : "\/htdocs\/log\/access\/*\/*.log"
```

Take a look in the documentation at point 3.1.2 
http://pimpmylog.com/documentation/configuration.html

**Comment by potsky** [comment]
You can limit the count of log files with the `count` parameter.
