### ISSUE TITLE
Oups! Please refresh the page.

### ISSUE THREAD

**Issue by amlwwalker** [potsky/PimpMyLog#101]
I have installed PimpMyLog and I can configure with the wizard when I go to the browser. When it completes config.user.php is created, but I get the error: 

![image](https://cloud.githubusercontent.com/assets/2920180/12628222/057eb04e-c53a-11e5-91f6-508794887b98.png)

Any ideas why?

**Comment by potsky** [comment]
Hi !

Absolutely no idea!

- Do you have an URL where I can check this ?
- Do you have errors in the browser javascript console ?
- Do you have errors in your PHP server logs ?

**Comment by michaelfeinbier** [comment]
Hi,

did you try to start PimpMyLog with the PHP embedded webserver? I have the same issue here. The browser javascript console is clear and no errors are visible in the stdout of the php embedded server

**Comment by potsky** [comment]
Hi,

> did you try to start PimpMyLog with the PHP embedded web server?

never... Is it a PHP7 feature?

Have you an URL that I could check ?

**Comment by potsky** [comment]
Ok, it works and I cannot get the *Oups!* error but I was obliged to modify the `configure.php` and `index.php` files to change `$_SERVER['QUERY_STRING']` to `@$_SERVER['QUERY_STRING']` because it seems the embedded PHP server does not populate this server parameter when empty.

I am really interested to get access to your pml instance to understand what is the problem...

```
php -S localhost:8080
PHP 5.5.31 Development Server started at Tue Feb 16 13:38:32 2016
Listening on http://localhost:8080
Document root is /...
Press Ctrl-C to quit.
[Tue Feb 16 13:39:51 2016] ::1:60924 [200]: /inc/configure.php?
[Tue Feb 16 13:39:51 2016] ::1:60926 [200]: /css/pml.min.css
[Tue Feb 16 13:39:51 2016] ::1:60929 [200]: /js/pml.min.js
[Tue Feb 16 13:39:51 2016] ::1:60930 [200]: /js/configure.min.js
[Tue Feb 16 13:39:51 2016] ::1:60932 [200]: /img/icon36.png
[Tue Feb 16 13:39:51 2016] ::1:60934 [200]: /inc/configure.php?1455626391880&
[Tue Feb 16 13:39:51 2016] ::1:60936 [200]: /fonts/ubuntu-l-webfont.woff
[Tue Feb 16 13:39:51 2016] ::1:60938 [200]: /inc/configure.php?1455626391902&
[Tue Feb 16 13:39:51 2016] ::1:60940 [200]: /css/pml.min.css.map
[Tue Feb 16 13:39:53 2016] ::1:60941 [200]: /inc/configure.php?1455626393281&
[Tue Feb 16 13:39:53 2016] ::1:60942 [200]: /inc/configure.php?1455626393287&
[Tue Feb 16 13:39:53 2016] ::1:60943 [200]: /fonts/ubuntumono-r-webfont.woff
[Tue Feb 16 13:39:55 2016] ::1:60944 [200]: /inc/configure.php?1455626395888&
[Tue Feb 16 13:39:57 2016] Pimp my Log has been successfully configured with Apache
[Tue Feb 16 13:39:57 2016] ::1:60945 [200]: /inc/configure.php?1455626397546&
[Tue Feb 16 13:40:51 2016] ::1:61005 [200]: /
[Tue Feb 16 13:40:51 2016] ::1:61006 [200]: /css/pml.min.css
[Tue Feb 16 13:40:51 2016] ::1:61007 [200]: /css/config.inc.css
[Tue Feb 16 13:40:51 2016] ::1:61008 [200]: /js/pml.min.js
[Tue Feb 16 13:40:51 2016] ::1:61009 [200]: /js/main.min.js
[Tue Feb 16 13:40:51 2016] ::1:61010 [200]: /img/loader.gif
[Tue Feb 16 13:40:51 2016] ::1:61011 [200]: /img/icon36.png
[Tue Feb 16 13:40:51 2016] ::1:61012 [200]: /img/inputclear.png
[Tue Feb 16 13:40:51 2016] ::1:61013 [200]: /css/hook-bgs.png
[Tue Feb 16 13:40:51 2016] ::1:61014 [200]: /inc/getlog.pml.php?1455626451159&null
[Tue Feb 16 13:40:51 2016] ::1:61015 [200]: /inc/upgrade.pml.php?1455626451161&null
[Tue Feb 16 13:40:51 2016] ::1:61016 [200]: /fonts/ubuntu-l-webfont.woff
[Tue Feb 16 13:40:51 2016] ::1:61017 [200]: /fonts/bootstrap/glyphicons-halflings-regular.woff
[Tue Feb 16 13:40:51 2016] ::1:61018 [200]: /fonts/ubuntumono-r-webfont.woff
[Tue Feb 16 13:40:51 2016] ::1:61019 [200]: /css/pml.min.css.map
[Tue Feb 16 13:40:56 2016] ::1:61022 [200]: /inc/getlog.pml.php?1455626456212&null
[Tue Feb 16 13:41:01 2016] ::1:61023 [200]: /inc/getlog.pml.php?1455626461231&null
[Tue Feb 16 13:41:06 2016] ::1:61025 [200]: /inc/getlog.pml.php?1455626466413&null
[Tue Feb 16 13:41:22 2016] ::1:61027 [200]: /inc/getlog.pml.php?1455626482408&null
...
```

**Comment by khromov** [comment]
Having same issue with built-in web server. Any fix planned? 

PS. This issue must have been introduced recently, because we have been running older versions of PML on the built-in web server without issues.

**Comment by khromov** [comment]
Bump! Any plans on fixing this?

**Comment by potsky** [comment]
Hi! I would like to fix it but I cannot reproduce this bug so it sounds a little bit complicated !

What is your environment ? OS, PHP version, etc... and check my questions on top on January.

**Comment by PtitPuce** [comment]
![pml_error](https://user-images.githubusercontent.com/40861759/55392842-5856e800-553c-11e9-9634-b7b3055208dc.png)
Same error here.

PHP 7.0.33-0+deb9u3 (cli) (built: Mar  8 2019 10:01:24) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies with Zend OPcache v7.0.33-0+deb9u3, Copyright (c) 1999-2017, by Zend Technologies

Server version: Apache/2.4.25 (Debian)
Server built:   2018-11-03T18:46:19

[VM] Debian  : debian-9.8.0-i386-netinst

OS : Win10 x64


Readibility of log files are ok, and the configuration ends up well.
The error only occurs when trying to display the LOGs.
I've checked what I could in /var/log/... and got no indication of error whatsoever.
Neither in the debug console of Firefox/Chrome, on both network and JsConsole tabs.
