### ISSUE TITLE
Feature Request: adding Port_URL (ip:port)

### ISSUE THREAD

**Issue by mmattel** [potsky/PimpMyLog#111]
In the way as you have http://www.geoiptool.com/en/?IP=%p"
there could be the same for ports like: http://www.adminsub.net/tcp-udp-port-finder/143

Means a new type like ``ip:port```pointing to the url above with the port as parameter.

This woud make port lookup easy

**Comment by potsky** [comment]
Hello, available in the 1.7.12 release in a few minutes.

The type will be `port` instead of `ip:port`.

Thank you for the good idea !

**Comment by mmattel** [comment]
Updated, configured, works :+1: 
Thanks a lot !
