### ISSUE TITLE
New config file examples available

### ISSUE THREAD

**Issue by mmattel** [potsky/PimpMyLog#112]
@potsky 
There are some updated and new config files available in the form I use them, ready to be used as example.
- just remove the ending .txt for those you want to use
- put file config.user.php in the root directory of PML
- put all other files into a directory called config.user.php.d as described in the manual
- adopt names and or file paths

Note syslog23 format is NOT enabled, default rsyslog format is used

[netapp 7.x.php.txt](https://github.com/potsky/PimpMyLog/files/780846/netapp.7.x.php.txt)
[nginx.php.txt](https://github.com/potsky/PimpMyLog/files/780847/nginx.php.txt)
[ubuntu_log.php.txt](https://github.com/potsky/PimpMyLog/files/780845/ubuntu_log.php.txt)
[zyxel_p2_plus_firewall.php.txt](https://github.com/potsky/PimpMyLog/files/780844/zyxel_p2_plus_firewall.php.txt)
[apc_ups.php.txt](https://github.com/potsky/PimpMyLog/files/780849/apc_ups.php.txt)
[cisco_35xx_accesspoint.php.txt](https://github.com/potsky/PimpMyLog/files/780851/cisco_35xx_accesspoint.php.txt)
[config.user.php.txt](https://github.com/potsky/PimpMyLog/files/780872/config.user.php.txt)
[owncloud.php.txt](https://github.com/potsky/PimpMyLog/files/780871/owncloud.php.txt)

**Comment by potsky** [comment]
Hey! Thank you very much for sharing!

I will include these files in a new directory inside the gh repo. Thank you !
