### ISSUE TITLE
globals.USER_TIME_ZONE not working

### ISSUE THREAD

**Issue by tito10047** [potsky/PimpMyLog#114]
when I set globals.USER_TIME_ZONE in config.user.json then is not working.

its problem because you include ```include_once 'inc/global.inc.php';``` in index.php on line 11 and inside this file is on end on line 1341 set timezone from constant. but constant is not loaded.

you load constant in ```index.php``` on line 67. so cant be working

**Comment by potsky** [comment]
Good job !

Will be fixed in next release
