### ISSUE TITLE
LOGS_REFRESH and LOGS_MAX not working

### ISSUE THREAD

**Issue by tito10047** [potsky/PimpMyLog#115]
Hi.
Im set this in my config.user.php
```json
"globals": {
    "LOGS_MAX": 50,
    "LOGS_REFRESH": 60,
}
```
but has not efect. when I open pimp then refresh is set to `no refresh` and logs is set to 10.

Im try modify global constant, but nothings changed.

**Comment by potsky** [comment]
I think that you have overwritten these settings in each `file` configuration with the `max` and the `effect` settings. Try to remove these settings and defaults will be used.

**Comment by tito10047** [comment]
yes. you have a right 👍 .
thanks.
