### ISSUE TITLE
unexpected T_FUNCTION, [PHP 5.2]

### ISSUE THREAD

**Issue by umbertix** [potsky/PimpMyLog#118]
PHP Parse error:  syntax error, unexpected T_FUNCTION, expecting ')' in /usr/local/www/apache22/data/dev-pimpmylog.com/inc/configure.php on line 47.

As explained in another thread the problem is to create a function and then use that new function in the error handler.

I did the change on my local files, but would be nice to fix it in the repo aswell.

**Comment by potsky** [comment]
Hi @umbertix,

can you send me your fix please ?

**Comment by umbertix** [comment]
On the line 47, replace for this:
`
function dumb_change($errno, $errstr, $errfile, $errline, array $errcontext) {
    throw new ErrorException($errstr, 0, $errno, $errfile, $errline);
};
set_error_handler("dumb_change");`

You probably want to rename the function name :)
