### ISSUE TITLE
make the link clikable

### ISSUE THREAD

**Issue by syrakozz** [potsky/PimpMyLog#97]
it will be great if we can click on the link in the URL column in the log (Apache access) so we can easily check it

**Comment by potsky** [comment]
Add type `uri` and `suri` which will just add a link to absolute link of the value (no IP or domain name)
Add type 'virtualhost' and 'svirtualhost'  and the argument is the field in which is stored the domain name.

`s` is for https instead of http

**Comment by syrakozz** [comment]
great tx
